language: python
dist: xenial
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- cd yzs_test
- python manage.py test
- cd ../
deploy:
  skip_existing: true
  provider: pypi
  user: wplct
  password:
    secure: b7xOA6+WwX16I9bT7G2X04HVD4KKxghW2888QZoKn+86WCp39y3xsAvr4t3v4EqefyoLIYxmkKL0fgoaAXIoLlioCOftXhm8sXEF2VUA6KNAZGyWQhiB+dGMQSA5oCTRnEk3u7MycLuCOM3zQvw1DcN4kYEeipgLRoPGF5D0wcTOotKRtpK/yhCzcKVnFyq98lphk73c3Z5gf2eX0Q0uRWLMNUa6IvKLUXkAV4ZPlT4lUmzLLIb2pH5Xl5p1ADCLDYmGnm0Ny8C479h8E4Wf1s9mYGqZBOzeUVWBGv9Ejqt9MT67SVFVfO0fD+zPe047eonQ0LTqLUEEJHBcv1IV6ASpKWNvMusdNWci33o0+LiqbGWAmWSsKAtccbAFqXFMLCbgDF/k9YwxaBpuyk8ObspH1hAF6aITKwLj//WyRDp3R3T5gx2t1Q0P/II5ZVEtg+8huQec7ryZXCQUgZNOJUxXlrdA64nQ9G0m/7Vq+Z8gtUfl1L+nkJ501k0J0io5tXQvC6PERc21htN9Kb+O+ROsI1Q7FW46WEAB4VtHWs8adCuMb1RI7oRARts+juUVQd1UYIj0szzvcxda3IGsFKjihvQjJPJ/iQhEsFB76LXLO0lssamTYrODI3F6vZfoNhgd7bRoA2EB710HNNOKJwcOjLG3ZIMSUXpjZic8DHg=
  true:
    branch: master
