# Generated by Django 2.2.1 on 2019-05-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_extend_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.IntegerField(choices=[(1, 'red'), (2, 'green')], default=1),
        ),
    ]
